Repository Make-A-Wish-Sopt/Make-A-Wish-Server, pull requests merged in 2023-08, with the labels that each got.

#66 [REFACT] 인증 인가 리팩토링
  src/main/java/com/sopterm/makeawish/common/ErrorHandler.java
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/config/SecurityConfig.java
  src/main/java/com/sopterm/makeawish/config/WebMvcConfig.java
  src/main/java/com/sopterm/makeawish/controller/filter/JwtAuthenticationFilter.java
  src/main/java/com/sopterm/makeawish/controller/filter/JwtExceptionFilter.java
  src/main/java/com/sopterm/makeawish/jwt/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/sopterm/makeawish/jwt/JwtAuthenticationFilter.java
Labels: sohyeon, fix

#69 [FIX] 인가 인증 경로 변경
  src/main/java/com/sopterm/makeawish/config/SecurityConfig.java
  src/main/java/com/sopterm/makeawish/controller/PresentController.java
  src/main/java/com/sopterm/makeawish/controller/PublicController.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeApproveRequestDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishResponseDTO.java
  src/main/java/com/sopterm/makeawish/service/CakeService.java
Labels: sohyeon, fix

#73 [REFACT] DB 리팩토링
  src/main/java/com/sopterm/makeawish/config/JpaAuditingConfig.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
  src/main/java/com/sopterm/makeawish/domain/BaseEntity.java
  src/main/java/com/sopterm/makeawish/domain/user/AccountInfo.java
  src/main/java/com/sopterm/makeawish/domain/user/User.java
  src/main/java/com/sopterm/makeawish/domain/wish/Wish.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeCreateResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/MainWishResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/MypageWishUpdateResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishRequestDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishResponseDTO.java
  src/main/java/com/sopterm/makeawish/service/CakeService.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, fix

#74 [FIX] 소원 링크 펀딩 종료 후 7일 연장
  build.gradle
  src/main/java/com/sopterm/makeawish/config/JpaQueryFactoryConfig.java
  src/main/java/com/sopterm/makeawish/dto/wish/MainWishResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishRequestDTO.java
  src/main/java/com/sopterm/makeawish/repository/WishRepository.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishCustomRepository.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishRepository.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishRepositoryImpl.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, fix

#75 [FEAT] 소원 단일 조회 API
  src/main/java/com/sopterm/makeawish/common/ErrorHandler.java
  src/main/java/com/sopterm/makeawish/common/Util.java
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
  src/main/java/com/sopterm/makeawish/dto/wish/MainWishResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/UserWishResponseDTO.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, feat

#76 [FEAT] 소원 모아보기 API
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishesResponseDTO.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishRepository.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, feat

#77 [FIX] 날짜 데이터 ISO 8601 형식 통일화
  src/main/java/com/sopterm/makeawish/dto/wish/WishRequestDTO.java
Labels: sohyeon, fix

#81 [FEAT] 소원 다중 삭제 API
  src/main/java/com/sopterm/makeawish/common/ErrorHandler.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishIdRequestDTO.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, feat

#83 [REFACT] 통일화 리팩토링
  src/main/java/com/sopterm/makeawish/common/ErrorHandler.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/config/SwaggerConfig.java
  src/main/java/com/sopterm/makeawish/controller/AuthController.java
  src/main/java/com/sopterm/makeawish/controller/CakeController.java
  src/main/java/com/sopterm/makeawish/controller/PublicController.java
  src/main/java/com/sopterm/makeawish/controller/TestController.java
  src/main/java/com/sopterm/makeawish/controller/UserController.java
  src/main/java/com/sopterm/makeawish/domain/user/KakaoTokenManager.java
  src/main/java/com/sopterm/makeawish/domain/user/User.java
  src/main/java/com/sopterm/makeawish/dto/auth/AuthGetTokenResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/auth/AuthSignInRequestDTO.java
  src/main/java/com/sopterm/makeawish/dto/auth/AuthSignInRequestDto.java
  src/main/java/com/sopterm/makeawish/dto/auth/AuthSignInResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeApproveResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeReadyRequestDTO.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeReadyResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/present/PresentDTO.java
  src/main/java/com/sopterm/makeawish/dto/present/PresentResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishResponseDTO.java
  src/main/java/com/sopterm/makeawish/service/AuthService.java
  src/main/java/com/sopterm/makeawish/service/CakeService.java
  src/main/java/com/sopterm/makeawish/service/SocialLoginService.java
  src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
Labels: sohyeon, fix

#85 [FIX] ISO 형식 오류 수정
  src/main/java/com/sopterm/makeawish/dto/wish/WishRequestDTO.java
Labels: sohyeon, fix

#86 [ADD] 예외 처리 추가
  src/main/java/com/sopterm/makeawish/common/Util.java
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/controller/PublicController.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishRequestDTO.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, add

#87 [FIX] 유저의 최신 소원보다 과거 소원을 생성할 수 없는 이슈 해결
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishRepositoryImpl.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, fix

#89 [FIX] 유저 예외처리 추가 적용
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/controller/UserController.java
  src/main/java/com/sopterm/makeawish/domain/user/AccountInfo.java
  src/main/java/com/sopterm/makeawish/domain/user/User.java
  src/main/java/com/sopterm/makeawish/domain/wish/Wish.java
  src/main/java/com/sopterm/makeawish/domain/wish/WishStatus.java
  src/main/java/com/sopterm/makeawish/dto/user/UserWishUpdateRequestDTO.java
  src/main/java/com/sopterm/makeawish/dto/user/UserWishUpdateResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/UserCurrentWishResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/UserWishUpdateRequestDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishRequestDTO.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishCustomRepository.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishRepository.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishRepositoryImpl.java
  src/main/java/com/sopterm/makeawish/service/UserService.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: fix, Yujindonut

#97 [FEAT] User 계좌정보 + 핸드폰정보 조회, 수정 API 생성
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/UserController.java
  src/main/java/com/sopterm/makeawish/domain/user/User.java
  src/main/java/com/sopterm/makeawish/dto/user/UserAccountResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/user/UserAccountUpdateRequestDTO.java
  src/main/java/com/sopterm/makeawish/service/UserService.java
Labels: feat, Yujindonut

#98 [FIX] 기능 수정 및 예외 처리
  src/main/java/com/sopterm/makeawish/common/ErrorHandler.java
  src/main/java/com/sopterm/makeawish/common/Util.java
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/domain/wish/Wish.java
  src/main/java/com/sopterm/makeawish/dto/wish/MainWishResponseDTO.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishCustomRepository.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishRepository.java
  src/main/java/com/sopterm/makeawish/repository/wish/WishRepositoryImpl.java
  src/main/java/com/sopterm/makeawish/service/UserService.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, fix

#100 [FIX] 시간 유효성 체크 수정
  src/main/java/com/sopterm/makeawish/common/Util.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishRequestDTO.java
  src/main/java/com/sopterm/makeawish/service/UserService.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, fix

#108 [FIX] 소원 수정 API 및 유저 정보 API 변동사항 적용
  src/main/java/com/sopterm/makeawish/controller/UserController.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
  src/main/java/com/sopterm/makeawish/domain/wish/Wish.java
  src/main/java/com/sopterm/makeawish/dto/user/UserAccountRequestDTO.java
  src/main/java/com/sopterm/makeawish/dto/user/UserAccountResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/user/UserWishUpdateRequestDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/UserWishUpdateRequestDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/UserWishUpdateResponseDTO.java
  src/main/java/com/sopterm/makeawish/service/UserService.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, fix

#111 [DEL] 파일 업로드 API 분리 반영
  src/main/java/com/sopterm/makeawish/controller/WishController.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, delete

#110 [FEAT] 이미지 업로드 구현
  build.gradle
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/config/S3Config.java
  src/main/java/com/sopterm/makeawish/controller/FileController.java
  src/main/java/com/sopterm/makeawish/service/FileService.java
Labels: feat, Yujindonut

#114 [CHORE] 소셜로그인시, 이메일 동의 하지 않았을 경우 이메일 제거
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/domain/user/KakaoTokenManager.java
Labels: chore, Yujindonut

#116 [ADD] 진행 중인 소원 조회 데이터 추가
  src/main/java/com/sopterm/makeawish/dto/wish/UserWishUpdateResponseDTO.java
Labels: sohyeon, add

#118 [DEL] 메인 소원 조회 이름 데이터 변경
  src/main/java/com/sopterm/makeawish/dto/wish/MainWishResponseDTO.java
Labels: sohyeon, fix

#120 [ADD] response 값 추가
  src/main/java/com/sopterm/makeawish/dto/auth/AuthSignInResponseDTO.java
  src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
Labels: chore, Yujindonut

#122 [TEST] 선물 결제하기 테스트
  .github/workflows/ci.yml
  .github/workflows/deploy-dev.yml
  src/test/java/com/sopterm/makeawish/service/CakeServiceTest.java
  src/test/resources/application.yml
Labels: wlwpfh

#124 [FIX] 토큰 검사 경로 추가
  src/main/java/com/sopterm/makeawish/config/SecurityConfig.java
Labels: fix, wlwpfh

#126 [FIX] 케이크 응답값 수정
  src/main/java/com/sopterm/makeawish/dto/present/PresentDTO.java
Labels: fix, wlwpfh

#128 [FIX] 생일자 이름 가져오기 수정
  src/main/java/com/sopterm/makeawish/service/CakeService.java
Labels: fix, wlwpfh

#134 [FEAT] 회원탈퇴 API
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/UserController.java
  src/main/java/com/sopterm/makeawish/service/UserService.java
Labels: sohyeon, feat

#136 [FIX] 소원 삭제 이슈 대응
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, fix
