Repository Make-A-Wish-Sopt/Make-A-Wish-Server, pull requests merged in 2023-12, with the labels that each got.

#144 [ADD] 휴대전화 및 계좌번호 암호화 로직 설정
  src/main/java/com/sopterm/makeawish/config/crypto/KeyEncrypt.java
  src/test/java/com/sopterm/makeawish/config/crypto/KeyEncryptTest.java
Labels: enhancement

#149 [FEAT] 계좌번호 이름 확인 구현
  build.gradle
  src/main/java/com/sopterm/makeawish/common/ErrorHandler.java
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/UserController.java
  src/main/java/com/sopterm/makeawish/service/UserService.java
  src/test/java/com/sopterm/makeawish/service/UserServiceTest.java
Labels: feat, wlwpfh

#154 [FIX] 예외 상태 코드 수정
  src/main/java/com/sopterm/makeawish/common/ErrorHandler.java
Labels: fix, wlwpfh

#156 [FEAT] 슬랙 알람 연동
  build.gradle
  src/main/java/com/sopterm/makeawish/config/FeignConfig.java
  src/main/java/com/sopterm/makeawish/external/SlackClient.java
  src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
Labels: Yujindonut, add

#158 [ADD] 소원 생성 시 슬랙 연동
  src/main/java/com/sopterm/makeawish/common/message/slack/SlackErrorMessage.java
  src/main/java/com/sopterm/makeawish/common/message/slack/SlackField.java
  src/main/java/com/sopterm/makeawish/common/message/slack/SlackSuccessMessage.java
  src/main/java/com/sopterm/makeawish/external/SlackWishClient.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
  src/main/java/com/sopterm/makeawish/service/social/KakaoLoginService.java
Labels: wlwpfh, add
