Repository Make-A-Wish-Sopt/Make-A-Wish-Server, pull requests merged in 2023-05, with the labels that each got.

#20 [CHORE] Swagger 연동
  build.gradle
  src/main/java/com/sopterm/makeawish/config/SecurityConfig.java
  src/main/java/com/sopterm/makeawish/config/SwaggerConfig.java
  src/main/java/com/sopterm/makeawish/config/WebMvcConfig.java
  src/main/java/com/sopterm/makeawish/controller/CakeController.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
Labels: sohyeon, chore

#22 [FEAT] 카카오페이 결제 승인 + 저장 API 구현
  src/main/java/com/sopterm/makeawish/common/KakaoPayProperties.java
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/CakeController.java
  src/main/java/com/sopterm/makeawish/domain/Present.java
  src/main/java/com/sopterm/makeawish/domain/wish/Wish.java
  src/main/java/com/sopterm/makeawish/dto/cake/Amount.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeApproveRequestDto.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeApproveResponseDto.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeCreateResponseDto.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeReadyRequestDto.java
  src/main/java/com/sopterm/makeawish/dto/cake/CardInfo.java
  src/main/java/com/sopterm/makeawish/repository/PresentRepository.java
  src/main/java/com/sopterm/makeawish/service/CakeService.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: feat, wlwpfh

#25 [HOTFIX] Token bug 수정
  src/main/java/com/sopterm/makeawish/config/jwt/JwtTokenFilter.java
  src/main/java/com/sopterm/makeawish/controller/AuthController.java
  src/main/java/com/sopterm/makeawish/controller/CakeController.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
Labels: fix, Yujindonut

#29 [FEAT] 마이페이지 유저정보 API
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/config/jwt/JwtTokenFilter.java
  src/main/java/com/sopterm/makeawish/controller/UserController.java
  src/main/java/com/sopterm/makeawish/domain/user/User.java
  src/main/java/com/sopterm/makeawish/domain/wish/Wish.java
  src/main/java/com/sopterm/makeawish/dto/wish/MypageWishUpdateRequestDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/MypageWishUpdateResponseDTO.java
  src/main/java/com/sopterm/makeawish/repository/WishRepository.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: feat, Yujindonut

#30 [FEAT] 소원 결과 상세 조회
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/config/jwt/JwtTokenFilter.java
  src/main/java/com/sopterm/makeawish/controller/CakeController.java
  src/main/java/com/sopterm/makeawish/domain/Cake.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/present/PresentDto.java
  src/main/java/com/sopterm/makeawish/service/CakeService.java
Labels: feat, wlwpfh

#32 [FIX] 결제 관련 수정
  src/main/java/com/sopterm/makeawish/common/ErrorHandler.java
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/config/jwt/JwtTokenFilter.java
  src/main/java/com/sopterm/makeawish/controller/CakeController.java
  src/main/java/com/sopterm/makeawish/service/CakeService.java
Labels: fix, wlwpfh

#37 [FIX] kakao 로그인시, error status code 추가
  src/main/java/com/sopterm/makeawish/service/AuthService.java
Labels: fix

#34 [FEAT] 케이크 편지 확인
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/CakeController.java
  src/main/java/com/sopterm/makeawish/dto/present/PresentResponseDto.java
  src/main/java/com/sopterm/makeawish/repository/PresentRepository.java
  src/main/java/com/sopterm/makeawish/service/CakeService.java
Labels: feat, wlwpfh

#40 [FIX] 결제 준비 라우터 수정
  src/main/java/com/sopterm/makeawish/config/SecurityConfig.java
  src/main/java/com/sopterm/makeawish/config/jwt/JwtTokenFilter.java
  src/main/java/com/sopterm/makeawish/controller/CakeController.java
  src/main/java/com/sopterm/makeawish/controller/PayController.java
Labels: fix, wlwpfh
