Repository Make-A-Wish-Sopt/Make-A-Wish-Server, pull requests merged in 2023-04, with the labels that each got.

#5 [CHORE] Entity 초기 설계
  .gitignore
  src/main/java/com/sopterm/makeawish/domain/Cake.java
  src/main/java/com/sopterm/makeawish/domain/Present.java
  src/main/java/com/sopterm/makeawish/domain/user/SocialType.java
  src/main/java/com/sopterm/makeawish/domain/user/User.java
  src/main/java/com/sopterm/makeawish/domain/wish/AccountInfo.java
  src/main/java/com/sopterm/makeawish/domain/wish/Wish.java
  src/main/java/com/sopterm/makeawish/dto/auth/AuthSignInRequestDto.java
  src/main/java/com/sopterm/makeawish/repository/UserRepository.java
  src/main/java/com/sopterm/makeawish/service/AuthService.java
  src/main/resources/application.yml
  src/main/resources/cakes/chicken.png
  src/main/resources/cakes/coffee.png
  src/main/resources/cakes/cow.png
  src/main/resources/cakes/dong.png
  src/main/resources/cakes/flower.png
  src/main/resources/cakes/perfume.png
  src/main/resources/cakes/sushi.png
  src/main/resources/cakes/vitamine.png
  src/test/java/com/sopterm/makeawish/MakeAWishApplicationTests.java
Labels: sohyeon, chore

#7 [FIX] Wish Entity 칼럼 변경
  src/main/java/com/sopterm/makeawish/domain/wish/Wish.java
Labels: sohyeon, fix

#9 [FEAT] 케이크 전체 조회 API 구현
  src/main/java/com/sopterm/makeawish/common/ApiResponse.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/AuthController.java
  src/main/java/com/sopterm/makeawish/controller/CakeController.java
  src/main/java/com/sopterm/makeawish/domain/Cake.java
  src/main/java/com/sopterm/makeawish/domain/user/User.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeResponseDTO.java
  src/main/java/com/sopterm/makeawish/repository/CakeRepository.java
  src/main/java/com/sopterm/makeawish/service/CakeService.java
Labels: sohyeon, feat

#12 [FEAT] 소원 링크 생성 API 구현
  src/main/java/com/sopterm/makeawish/common/ErrorHandler.java
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/config/SecurityConfig.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
  src/main/java/com/sopterm/makeawish/domain/user/User.java
  src/main/java/com/sopterm/makeawish/domain/wish/AccountInfo.java
  src/main/java/com/sopterm/makeawish/domain/wish/Wish.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishRequestDTO.java
  src/main/java/com/sopterm/makeawish/repository/WishRepository.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, feat

#16 [FEAT] 소원 링크 조회 API 구현
  src/main/java/com/sopterm/makeawish/common/message/ErrorMessage.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/config/SecurityConfig.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
  src/main/java/com/sopterm/makeawish/domain/wish/AccountInfo.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishResponseDTO.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, feat

#17 [FEAT] 카카오결제 준비 API 구현
  src/main/java/com/sopterm/makeawish/common/KakaoPayProperties.java
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/CakeController.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeReadyRequestDto.java
  src/main/java/com/sopterm/makeawish/dto/cake/CakeReadyResponseDto.java
  src/main/java/com/sopterm/makeawish/service/CakeService.java
Labels: feat, wlwpfh

#19 [FEAT] 메인 화면 조회 API 구현
  src/main/java/com/sopterm/makeawish/common/message/SuccessMessage.java
  src/main/java/com/sopterm/makeawish/controller/WishController.java
  src/main/java/com/sopterm/makeawish/dto/wish/MainWishResponseDTO.java
  src/main/java/com/sopterm/makeawish/dto/wish/WishResponseDTO.java
  src/main/java/com/sopterm/makeawish/repository/WishRepository.java
  src/main/java/com/sopterm/makeawish/service/WishService.java
Labels: sohyeon, feat
